import React, { useState } from "react";
import { jsPDF } from "jspdf";
import autoTable from "jspdf-autotable";

export default function Step6Complete({ email ,onNext,onBack,onContinue}) {
    const [show,setShow] = useState(false)
    const handleSubmit = (e) => {
        e.preventDefault();
        // ✅ No backend call — just move to the next step
        onNext();
    };
    const handleSubmit2 = (e) => {
        e.preventDefault();
        // ✅ No backend call — just move to the next step
        onContinue();
    };
    const handleDownload = () => {
        const doc = new jsPDF();

        // Title
        doc.setFont("helvetica", "bold");
        doc.setFontSize(20);
        doc.text("Capsule Collection Brief", 20, 25);

        // Subtitle
        doc.setFontSize(12);
        doc.setFont("helvetica", "normal");
        doc.setTextColor(100);
        doc.text(`Prepared for: ${email}`, 20, 35);

        // Summary section
        autoTable(doc, {
            startY: 45,
            head: [["Section", "Details"]],
            body: [
                ["Summary", "A versatile and cohesive collection focused on clean lines and seasonal transition."],
                ["Fabric Suggestions", "Organic Cotton, Linen, Tencel"],
                ["Color Palette", "Ivory, Sand, Olive Green, Black"],
                ["Construction Notes", "French seams, sustainable dyeing, quality hardware"],
            ],
            styles: {
                fontSize: 10,
                cellPadding: 6,
                textColor: "#111",
                lineColor: "#eee",
                lineWidth: 0.3,
            },
            headStyles: {
                fillColor: "#000000",
                textColor: "#ffffff",
            },
        });

        // Footer
        doc.setFontSize(10);
        doc.setTextColor(150);
        doc.text("Generated by Capsule Builder · formdepartment.com", 20, doc.internal.pageSize.height - 10);

        // Save
        doc.save("capsule-tech-pack.pdf");
    };

    const handleUpgrade = () => {
        alert("Redirect to upgrade logic...");
    };
    const handleClick= ()=> {
          setShow((prev) => !prev);
    }
    return (
        <div className="max-w-md mx-auto p-8 border border-white bg-white/60 backdrop-blur-md rounded-lg shadow-lg">
           <button
           type = "button"
                    onClick={onBack}
                   className=" pb-1 text-xl font-semibold text-[#8c7152] ">

               ←
           </button>
           {/*
            <p className="pt-1 text-sm text-white/60 mb-2 font-sans leading-[1.2]">
                Form Department — <span className="text-white">Capsule Builder</span>
            </p>
           */}

            <h2 className="text-3xl mb-4 font-heading text-black leading-[1.2]">Want expert eyes on your capsule?</h2>

            <p className="text-sm text-black/70 mb-4">
                Add professional review or complete tech pack service.
            </p>

  {/*          <ul className="text-sm list-disc list-inside space-y-1 mb-6">
                <li>Summary of your ideas</li>
                <li>Fabric suggestions</li>
                <li>Color palette</li>
                <li>Construction notes</li>
            </ul>
*/}
            <button
                onClick={onNext}
                className="w-full  text-white py-3 text-sm font-medium bg-[#b89d7b] hover:bg-[#a98a67] active:bg-[#8c7152] transition rounded"
            >
                Add Expert Review
            </button>
            <div>
            <button
                onClick={onContinue}
                className="w-full border border-gray-300 text-white py-3 text-sm mt-4 bg-[#b89d7b] hover:bg-[#a98a67] active:bg-[#8c7152]  rounded"
            >
                Continue Free
            </button>
 </div>
           { /*<p className="text-xs text-white/50 mt-2 text-center">🔒 Upgrade your plan to unlock this feature</p>

            <button
                onClick={handleUpgrade}
                className="mt-4 w-full border border-white text-white py-2 text-sm hover:bg-white/10 transition rounded"
            >
                Upgrade Plan
            </button>
            */}
        </div>
    );
}
