import React from "react";
import { jsPDF } from "jspdf";
import autoTable from "jspdf-autotable";

export default function Step6Complete({ email ,onBack}) {
    const handleDownload = () => {
        const doc = new jsPDF();

        // Title
        doc.setFont("helvetica", "bold");
        doc.setFontSize(20);
        doc.text("Capsule Collection Brief", 20, 25);

        // Subtitle
        doc.setFontSize(12);
        doc.setFont("helvetica", "normal");
        doc.setTextColor(100);
        doc.text(`Prepared for: ${email}`, 20, 35);

        // Summary section
        autoTable(doc, {
            startY: 45,
            head: [["Section", "Details"]],
            body: [
                ["Summary", "A versatile and cohesive collection focused on clean lines and seasonal transition."],
                ["Fabric Suggestions", "Organic Cotton, Linen, Tencel"],
                ["Color Palette", "Ivory, Sand, Olive Green, Black"],
                ["Construction Notes", "French seams, sustainable dyeing, quality hardware"],
            ],
            styles: {
                fontSize: 10,
                cellPadding: 6,
                textColor: "#111",
                lineColor: "#eee",
                lineWidth: 0.3,
            },
            headStyles: {
                fillColor: "#000000",
                textColor: "#ffffff",
            },
        });

        // Footer
        doc.setFontSize(10);
        doc.setTextColor(150);
        doc.text("Generated by Capsule Builder · formdepartment.com", 20, doc.internal.pageSize.height - 10);

        // Save
        doc.save("capsule-tech-pack.pdf");
    };

    const handleUpgrade = () => {
        alert("Redirect to upgrade logic...");
    };

    return (
        <div className="max-w-md mx-auto p-8 border border-white bg-black/60 backdrop-blur-md rounded-lg shadow-lg">
           <button
           type = "button"
                    onClick={onBack}
                   className=" pb-1 text-xl font-semibold ">

               ←
           </button>
            <p className="pt-1 text-sm text-white/60 mb-2 font-[Garamond]">
                Form Department — <span className="text-white">Capsule Builder</span>
            </p>

            <h2 className="text-3xl mb-6 font-normal font-[Garamond]">Next Steps:</h2>
{/*
            <p className="text-sm text-white/70 mb-4">
                We’ve prepared the following for your capsule:
            </p>

            <ul className="text-sm list-disc list-inside space-y-1 mb-6">
                <li>Summary of your ideas</li>
                <li>Fabric suggestions</li>
                <li>Color palette</li>
                <li>Construction notes</li>
            </ul>
*/}
            <button
                onClick={handleDownload}
                className="w-full bg-white text-black py-3 text-sm font-medium hover:bg-gray-200 transition rounded"
            >
                Download Summary
            </button>

            <button
                disabled
                className="w-full border border-gray-300 text-gray-400 py-3 text-sm mt-4 bg-gray-100 cursor-not-allowed"
            >
                Get Expert Feedback
            </button>

            <p className="text-xs text-white/50 mt-2 text-center">🔒 Upgrade your plan to unlock this feature</p>

            <button
                onClick={handleUpgrade}
                className="mt-4 w-full border border-white text-white py-2 text-sm hover:bg-white/10 transition rounded"
            >
                Upgrade Plan
            </button>
        </div>
    );
}
